name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: path
      run:  ls
    - name: build
      run: mkdir build && cd build
    - name: build
      run: cmake -G "Unix Makefiles"  -DCMAKE_BUILD_TYPE=Debug 
    - name: make 
      run: make -j$(nproc)
