name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: build
      run: mkdir Kalido-comp/build
    - name:  build
      run: cd Kalido-comp/build
    - name: build
      run: cmake .. -G "Unix Makefiles"  -DCMAKE_BUILD_TYPE=Debug 
    - name: make 
      run: make -j$(nproc)
